### ISSUE TITLE
Obrigado mano por ter me apresentado a JetBrains Academy

### ISSUE THREAD

**Issue by EufranioDiogo** [GuilhermeMGarcia/Zookeeper#1]
Valeu! É massa a academy! Abraços e continuação de bons estudos.

**Comment by GuilhermeMGarcia** [comment]
@EufranioDiogo por nada amigo, sou iniciante na Academy tbm, caso queira criar um grupo no whats com alguns parceiro que vc conhece eu estaria disponível pois estou solo nessa jornada de estudos.

**Comment by EufranioDiogo** [comment]
Hello @GuilhermeMGarcia! espero que esteja tudo bem consigo! Nessa jornada eu também tenho andando sozinho e a sua ideia é muito joia, mas como já disse também estou sozinho! Já estou a um tempo nesta jornada e procurando melhorar as minhas habilidades em Python particularmente, e estou disponível para criar novas ligações sobre programação e podiamos nos ajudar mutuamente!

Aqui está o meu contacto: **+244 921 611 793**. Pode puxar quando quiser amigo.

Forças e abraços!
